### PR TITLE
Added dotenv npm module, local development now working

### PR DESCRIPTION
**Pull request by HebaNAS**
Notice that this will need unique wml service credentials in .env file, so may still break if running locally unless you provide your own .env variables. I have not checked mine in this repo.

If the app is deployed to the cloud it should grab the required credentials from VCAP.

In the readme I will add detailed steps on how to create a .env file and plug that into the application. I'm working on that now.

### CODE REVIEW

**Comment by stevemart** [comment]
@HebaNAS hmm, did you intend to push this to the master branch?

**Comment by scottdangelo** [comment]
@HebaNAS It is great to use a branch, and then merge that into Master with a Pull request. But your uiBranch is behind master:
image

If you can rebase your uiBranch against the latest master:
```
git checkout uiBranch    #Checkout your branch
git fetch origin            # Updates origin/master
git rebase origin/master    # Rebases current branch onto origin/master
```

Then you can add these changes directly to your uiBranch, and then create a pull request to merge this uiBranch into Master.

**Comment by HebaNAS** [comment]
@scottdangelo, I don't know if the edits committed now are ok or not. I have worked further on this branch and still have uncompleted work that was committed.
Please let me know if this can pass or do I need to revert back and clean up things.

**Comment by scottdangelo** [comment]
Since this is on a branch, it is fine to merge.
You can always merge your code directly on a branch in this repository.
We only want to be careful when we merge into the Master branch.

**Pull request merged**
